String selectCountryCode = 'US';

const countryCode = [
  'US',
  'CA',
  'RU',
  'KZ',
  'EG',
  'ZA',
  'GR',
  'NL',
  'BE',
  'FR',
  'ES',
  'HU',
  'IT',
  'RO',
  'CH',
  'AT',
  'GB',
  'DK',
  'SE',
  'NO',
  'PL',
  'DE',
  'PE',
  'MX',
  'CU',
  'AR',
  'BR',
  'CL',
  'CO',
  'VE',
  'MY',
  'AU',
  'ID',
  'PH',
  'NZ',
  'SG',
  'TH',
  'JP',
  'KR',
  'VN',
  'CN',
  'TR',
  'IN',
  'PK',
  'AF',
  'LK',
  'MM',
  'IR',
  'SS',
  'MA',
  'EH',
  'DZ',
  'TN',
  'LY',
  'GM',
  'SN',
  'MR',
  'ML',
  'GN',
  'CI',
  'BF',
  'NE',
  'TG',
  'BJ',
  'MU',
  'LR',
  'SL',
  'GH',
  'NG',
  'TD',
  'CF',
  'CM',
  'CV',
  'GQ',
  'GA',
  'CG',
  'CD',
  'AO',
  'GW',
  'SC',
  'SD',
  'RW',
  'ET',
  'SO',
  'DJ',
  'KE',
  'TZ',
  'UG',
  'BI',
  'MZ',
  'ZM',
  'MG',
  'ZW',
  'NA',
  'MW',
  'LS',
  'BW',
  'SZ',
  'YT',
  'KM',
  'SH',
  'ER',
  'AW',
  'GL',
  'GI',
  'PT',
  'LU',
  'IE',
  'IS',
  'AL',
  'MT',
  'CY',
  'FI',
  'BG',
  'LT',
  'LV',
  'EE',
  'MD',
  'AM',
  'BY',
  'AD',
  'MC',
  'SM',
  'VA',
  'UA',
  'RS',
  'ME',
  'HR',
  'SI',
  'BA',
  'MK',
  'CZ',
  'SK',
  'LI',
  'FK',
  'BZ',
  'GT',
  'SV',
  'HN',
  'NI',
  'CR',
  'PA',
  'PM',
  'HT',
  'GP',
  'BO',
  'GY',
  'EC',
  'PY',
  'MQ',
  'SR',
  'UY',
  'TL',
  'BN',
  'NR',
  'PG',
  'TO',
  'SB',
  'VU',
  'FJ',
  'PW',
  'CK',
  'NU',
  'WS',
  'KI',
  'NC',
  'TV',
  'TK',
  'FM',
  'MH',
  'KP',
  'HK',
  'MO',
  'KH',
  'LA',
  'BD',
  'TW',
  'MV',
  'LB',
  'JO',
  'SY',
  'IQ',
  'KW',
  'SA',
  'YE',
  'OM',
  'PS',
  'AE',
  'IL',
  'BH',
  'QA',
  'BT',
  'MN',
  'NP',
  'TJ',
  'TM',
  'AZ',
  'GE',
  'KG',
  'UZ',
  'BS',
  'BB',
  'AI',
  'AG',
  'KY',
  'BM',
  'GD',
  'MS',
  'GU',
  'AS',
  'SX',
  'LC',
  'DM',
  'PR',
  'DO',
  'TT',
  'JM'
];

const countryToNumber = {
  'US': '+1',
  'CA': '+1',
  'RU': '+7',
  'KZ': '+7',
  'EG': '+20',
  'ZA': '+27',
  'GR': '+30',
  'NL': '+31',
  'BE': '+32',
  'FR': '+33',
  'ES': '+34',
  'HU': '+36',
  'IT': '+39',
  'RO': '+40',
  'CH': '+41',
  'AT': '+43',
  'GB': '+44',
  'DK': '+45',
  'SE': '+46',
  'NO': '+47',
  'PL': '+48',
  'DE': '+49',
  'PE': '+51',
  'MX': '+52',
  'CU': '+53',
  'AR': '+54',
  'BR': '+55',
  'CL': '+56',
  'CO': '+57',
  'VE': '+58',
  'MY': '+60',
  'AU': '+61',
  'ID': '+62',
  'PH': '+63',
  'NZ': '+64',
  'SG': '+65',
  'TH': '+66',
  'JP': '+81',
  'KR': '+82',
  'VN': '+84',
  'CN': '+86',
  'TR': '+90',
  'IN': '+91',
  'PK': '+92',
  'AF': '+93',
  'LK': '+94',
  'MM': '+95',
  'IR': '+98',
  'SS': '+211',
  'MA': '+212',
  'EH': '+212',
  'DZ': '+213',
  'TN': '+216',
  'LY': '+218',
  'GM': '+220',
  'SN': '+221',
  'MR': '+222',
  'ML': '+223',
  'GN': '+224',
  'CI': '+225',
  'BF': '+226',
  'NE': '+227',
  'TG': '+228',
  'BJ': '+229',
  'MU': '+230',
  'LR': '+231',
  'SL': '+232',
  'GH': '+233',
  'NG': '+234',
  'TD': '+235',
  'CF': '+236',
  'CM': '+237',
  'CV': '+238',
  'GQ': '+240',
  'GA': '+241',
  'CG': '+242',
  'CD': '+243',
  'AO': '+244',
  'GW': '+245',
  'SC': '+248',
  'SD': '+249',
  'RW': '+250',
  'ET': '+251',
  'SO': '+252',
  'DJ': '+253',
  'KE': '+254',
  'TZ': '+255',
  'UG': '+256',
  'BI': '+257',
  'MZ': '+258',
  'ZM': '+260',
  'MG': '+261',
  'ZW': '+263',
  'NA': '+264',
  'MW': '+265',
  'LS': '+266',
  'BW': '+267',
  'SZ': '+268',
  'YT': '+269',
  'KM': '+269',
  'SH': '+290',
  'ER': '+291',
  'AW': '+297',
  'GL': '+299',
  'GI': '+350',
  'PT': '+351',
  'LU': '+352',
  'IE': '+353',
  'IS': '+354',
  'AL': '+355',
  'MT': '+356',
  'CY': '+357',
  'FI': '+358',
  'BG': '+359',
  'LT': '+370',
  'LV': '+371',
  'EE': '+372',
  'MD': '+373',
  'AM': '+374',
  'BY': '+375',
  'AD': '+376',
  'MC': '+377',
  'SM': '+378',
  'VA': '+379',
  'UA': '+380',
  'RS': '+381',
  'ME': '+382',
  'HR': '+385',
  'SI': '+386',
  'BA': '+387',
  'MK': '+389',
  'CZ': '+420',
  'SK': '+421',
  'LI': '+423',
  'FK': '+500',
  'BZ': '+501',
  'GT': '+502',
  'SV': '+503',
  'HN': '+504',
  'NI': '+505',
  'CR': '+506',
  'PA': '+507',
  'PM': '+508',
  'HT': '+509',
  'GP': '+590',
  'BO': '+591',
  'GY': '+592',
  'EC': '+593',
  'PY': '+595',
  'MQ': '+596',
  'SR': '+597',
  'UY': '+598',
  'TL': '+670',
  'BN': '+673',
  'NR': '+674',
  'PG': '+675',
  'TO': '+676',
  'SB': '+677',
  'VU': '+678',
  'FJ': '+679',
  'PW': '+680',
  'CK': '+682',
  'NU': '+683',
  'WS': '+685',
  'KI': '+686',
  'NC': '+687',
  'TV': '+688',
  'TK': '+690',
  'FM': '+691',
  'MH': '+692',
  'KP': '+850',
  'HK': '+852',
  'MO': '+853',
  'KH': '+855',
  'LA': '+856',
  'BD': '+880',
  'TW': '+886',
  'MV': '+960',
  'LB': '+961',
  'JO': '+962',
  'SY': '+963',
  'IQ': '+964',
  'KW': '+965',
  'SA': '+966',
  'YE': '+967',
  'OM': '+968',
  'PS': '+970',
  'AE': '+971',
  'IL': '+972',
  'BH': '+973',
  'QA': '+974',
  'BT': '+975',
  'MN': '+976',
  'NP': '+977',
  'TJ': '+992',
  'TM': '+993',
  'AZ': '+994',
  'GE': '+995',
  'KG': '+996',
  'UZ': '+998',
  'BS': '+1242',
  'BB': '+1246',
  'AI': '+1264',
  'AG': '+1268',
  'KY': '+1345',
  'BM': '+1441',
  'GD': '+1473',
  'MS': '+1664',
  'GU': '+1671',
  'AS': '+1684',
  'SX': '+1721',
  'LC': '+1758',
  'DM': '+1767',
  'PR': '+1787',
  'DO': '+1809',
  'TT': '+1868',
  'JM': '+1876',
};

const countryToEn = {
  'US': 'United States of America',
  'CA': 'Canada',
  'RU': 'Russia',
  'KZ': 'Kazakstan',
  'EG': 'Egypt',
  'ZA': 'South Africa',
  'GR': 'Greece',
  'NL': 'the Netherlands',
  'BE': 'Belgium',
  'FR': 'France',
  'ES': 'Spain',
  'HU': 'Hungary',
  'IT': 'Italy',
  'RO': 'Romania',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'GB': 'United Kingdom',
  'DK': 'Denmark',
  'SE': 'Sweden',
  'NO': 'Norway',
  'PL': 'Poland',
  'DE': 'Germany',
  'PE': 'Peru',
  'MX': 'Mexico',
  'CU': 'Cuba',
  'AR': 'Argentina',
  'BR': 'Brazil',
  'CL': 'Chile',
  'CO': 'Colombia',
  'VE': 'Venezuela',
  'MY': 'Malaysia',
  'AU': 'Australia',
  'ID': 'Indonesia',
  'PH': 'the Philippines',
  'NZ': 'New Zealand',
  'SG': 'Singapore',
  'TH': 'Thailand',
  'JP': 'Japan',
  'KR': 'Republic of Korea',
  'VN': 'Vietnam',
  'CN': 'China',
  'TR': 'Turkey',
  'IN': 'India',
  'PK': 'Pakistan',
  'AF': 'Afghanistan',
  'LK': 'Sri Lanka',
  'MM': 'Myanmar',
  'IR': 'Iran',
  'SS': 'South Sudan',
  'MA': 'Morocco',
  'EH': 'Western Sahara',
  'DZ': 'Algeria',
  'TN': 'Tunisia',
  'LY': 'Libya',
  'GM': 'Gambia',
  'SN': 'Senegal',
  'MR': 'Mauritania',
  'ML': 'Mali',
  'GN': 'Guinea',
  'CI': 'Ivory Coast',
  'BF': 'Burkina Faso',
  'NE': 'Niger',
  'TG': 'Togo',
  'BJ': 'Benin',
  'MU': 'Mauritius',
  'LR': 'Liberia',
  'SL': 'Sierra Leone',
  'GH': 'Ghana',
  'NG': 'Nigeria',
  'TD': 'Chad',
  'CF': 'Central Africa',
  'CM': 'Cameroon',
  'CV': 'Cape Verde',
  'GQ': 'Equatorial Guinea',
  'GA': 'Gabon',
  'CG': 'Congo',
  'CD': 'DR Congo',
  'AO': 'Angola',
  'GW': 'Guinea-Bissau',
  'SC': 'Seychelles',
  'SD': 'Sudan',
  'RW': 'Rwanda',
  'ET': 'Ethiopia',
  'SO': 'Somalia',
  'DJ': 'Djibouti',
  'KE': 'Kenya',
  'TZ': 'Tanzania',
  'UG': 'Uganda',
  'BI': 'Burundi',
  'MZ': 'Mozambique',
  'ZM': 'Zambia',
  'MG': 'Madagascar',
  'ZW': 'Zimbabwe',
  'NA': 'Namibia',
  'MW': 'Malawi',
  'LS': 'Lesotho',
  'BW': 'Botswana',
  'SZ': 'Eswatini',
  'YT': 'Mayotte',
  'KM': 'the Comoros',
  'SH': 'Saint Helena',
  'ER': 'Eritrea',
  'AW': 'Aruba',
  'GL': 'Greenland',
  'GI': 'Gibraltar',
  'PT': 'Portugal',
  'LU': 'Luxembourg',
  'IE': 'Ireland',
  'IS': 'Iceland',
  'AL': 'Albania',
  'MT': 'Malta',
  'CY': 'Cyprus',
  'FI': 'Finland',
  'BG': 'Bulgaria',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'EE': 'Estonia',
  'MD': 'Maldova',
  'AM': 'Armenia',
  'BY': 'Belarus',
  'AD': 'Andorra',
  'MC': 'Monaco',
  'SM': 'San Marino',
  'VA': 'Vatican',
  'UA': 'Ukraine',
  'RS': 'Serbia',
  'ME': 'Montenegro',
  'HR': 'Croatia',
  'SI': 'Slovenia',
  'BA': 'Bosnia and Herzegovina',
  'MK': 'Macedonia',
  'CZ': 'Czech',
  'SK': 'Slovakia',
  'LI': 'Liechtenstein',
  'FK': 'Falkland Islands',
  'BZ': 'Belize',
  'GT': 'Guatemala',
  'SV': 'El Salvador',
  'HN': 'Honduras',
  'NI': 'Nicaragua',
  'CR': 'Costa Rica',
  'PA': 'Panama',
  'PM': 'Saint Pierre and Miquelon',
  'HT': 'Haiti',
  'GP': 'Guadeloupe',
  'BO': 'Bolivia',
  'GY': 'Guyana',
  'EC': 'Ecuador',
  'PY': 'Paraguay',
  'MQ': 'Martinique',
  'SR': 'Suriname',
  'UY': 'Uruguay',
  'TL': 'East Timor',
  'BN': 'Brunei',
  'NR': 'Nauru',
  'PG': 'Papua New Guinea',
  'TO': 'Tonga',
  'SB': 'Solomon Islands',
  'VU': 'Vanuatu',
  'FJ': 'Fiji',
  'PW': 'Palau',
  'CK': 'Cook Islands',
  'NU': 'Niue',
  'WS': 'Samoa',
  'KI': 'Kiribati',
  'NC': 'New Caledonia',
  'TV': 'Tuvalu',
  'TK': 'Tokelau',
  'FM': 'Micronesia',
  'MH': 'Marshall Islands',
  'KP': 'DPR of Korea',
  'HK': 'Hong Kong',
  'MO': 'Macao',
  'KH': 'Cambodia',
  'LA': 'Laos',
  'BD': 'Bangladesh',
  'TW': 'Taiwan',
  'MV': 'Maldives',
  'LB': 'Lebanon',
  'JO': 'Jordan',
  'SY': 'Syria',
  'IQ': 'Iraq',
  'KW': 'Kuwait',
  'SA': 'Saudi Arabia',
  'YE': 'Yemen',
  'OM': 'Oman',
  'PS': 'State of Palestine',
  'AE': 'United Arab Emirates',
  'IL': 'Israel',
  'BH': 'Bahrain',
  'QA': 'Qatar',
  'BT': 'Bhutan',
  'MN': 'Mongolia',
  'NP': 'Nepal',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'AZ': 'Azerbaijan',
  'GE': 'Georgia',
  'KG': 'Kyrgizstan',
  'UZ': 'Uzbekistan',
  'BS': 'Bahamas',
  'BB': 'Barbados',
  'AI': 'Anguilla',
  'AG': 'Antigua and Barbuda',
  'KY': 'Cayman Islands',
  'BM': 'Bermuda',
  'GD': 'Grenada',
  'MS': 'Montserrat',
  'GU': 'Guam',
  'AS': 'American Samoa',
  'SX': 'Sint Maarten',
  'LC': 'Saint Lucia',
  'DM': 'Dominica',
  'PR': 'Puerto Rico',
  'DO': 'Dominican R.',
  'TT': 'Trinidad and Tobago',
  'JM': 'Jamaica',
};

const countryToKr = {
  'US': '미국',
  'CA': '캐나다',
  'RU': '러시아',
  'KZ': '카자흐스탄',
  'EG': '이집트',
  'ZA': '남아프리카 공화국',
  'GR': '그리스',
  'NL': '네덜란드',
  'BE': '벨기에',
  'FR': '프랑스',
  'ES': '스페인',
  'HU': '헝가리',
  'IT': '이탈리아',
  'RO': '루마니아',
  'CH': '스위스',
  'AT': '오스트리아',
  'GB': '영국',
  'DK': '덴마크',
  'SE': '스웨덴',
  'NO': '노르웨이',
  'PL': '폴란드',
  'DE': '독일',
  'PE': '페루',
  'MX': '멕시코',
  'CU': '쿠바',
  'AR': '아르헨티나',
  'BR': '브라질',
  'CL': '칠레',
  'CO': '콜롬비아',
  'VE': '베네수엘라',
  'MY': '말레이시아',
  'AU': '오스트레일리아',
  'ID': '인도네시아',
  'PH': '필리핀',
  'NZ': '뉴질랜드',
  'SG': '싱가포르',
  'TH': '태국',
  'JP': '일본',
  'KR': '대한민국',
  'VN': '베트남',
  'CN': '중화인민공화국',
  'TR': '터키',
  'IN': '인도',
  'PK': '파키스탄',
  'AF': '아프가니스탄',
  'LK': '스리랑카',
  'MM': '미얀마',
  'IR': '이란',
  'SS': '남수단',
  'MA': '모로코',
  'EH': '서사하라',
  'DZ': '알제리',
  'TN': '튀니지',
  'LY': '리비아',
  'GM': '감비아',
  'SN': '세네갈',
  'MR': '모리타니',
  'ML': '말리',
  'GN': '기니',
  'CI': '코트디부아르',
  'BF': '부르키나파소',
  'NE': '니제르',
  'TG': '토고',
  'BJ': '베냉',
  'MU': '모리셔스',
  'LR': '라이베리아',
  'SL': '시에라리온',
  'GH': '가나',
  'NG': '나이지리아',
  'TD': '차드',
  'CF': '중앙아프리카 공화국',
  'CM': '카메룬',
  'CV': '카보베르데',
  'GQ': '적도 기니',
  'GA': '가봉',
  'CG': '콩고 공화국',
  'CD': '콩고 민주 공화국',
  'AO': '앙골라',
  'GW': '기니비사우',
  'SC': '세이셸',
  'SD': '수단',
  'RW': '르완다',
  'ET': '에티오피아',
  'SO': '소말리아',
  'DJ': '지부티',
  'KE': '케냐',
  'TZ': '탄자니아',
  'UG': '우간다',
  'BI': '부룬디',
  'MZ': '모잠비크',
  'ZM': '잠비아',
  'MG': '마다가스카르',
  'ZW': '짐바브웨',
  'NA': '나미비아',
  'MW': '말라위',
  'LS': '레소토',
  'BW': '보츠와나',
  'SZ': '에스와티니',
  'YT': '마요트',
  'KM': '코모로',
  'SH': '세인트헬레나',
  'ER': '에리트레아',
  'AW': '아루바',
  'GL': '그린란드',
  'GI': '지브롤터',
  'PT': '포르투갈',
  'LU': '룩셈부르크',
  'IE': '아일랜드',
  'IS': '아이슬란드',
  'AL': '알바니아',
  'MT': '몰타',
  'CY': '키프로스',
  'FI': '핀란드',
  'BG': '불가리아',
  'LT': '리투아니아',
  'LV': '라트비아',
  'EE': '에스토니아',
  'MD': '몰도바',
  'AM': '아르메니아',
  'BY': '벨라루스',
  'AD': '안도라',
  'MC': '모나코',
  'SM': '산마리노',
  'VA': '바티칸 시국',
  'UA': '우크라이나',
  'RS': '세르비아',
  'ME': '몬테네그로',
  'HR': '크로아티아',
  'SI': '슬로베니아',
  'BA': '보스니아 헤르체고비나',
  'MK': '북마케도니아',
  'CZ': '체코',
  'SK': '슬로바키아',
  'LI': '리히텐슈타인',
  'FK': '포클랜드 제도',
  'BZ': '벨리즈',
  'GT': '과테말라',
  'SV': '엘살바도르',
  'HN': '온두라스',
  'NI': '니카라과',
  'CR': '코스타리카',
  'PA': '파나마',
  'PM': '생피에르 미클롱',
  'HT': '아이티',
  'GP': '과들루프',
  'BO': '볼리비아',
  'GY': '가이아나',
  'EC': '에콰도르',
  'PY': '파라과이',
  'MQ': '마르티니크',
  'SR': '수리남',
  'UY': '우루과이',
  'TL': '동티모르',
  'BN': '브루나이',
  'NR': '나우루',
  'PG': '파푸아뉴기니',
  'TO': '통가',
  'SB': '솔로몬 제도',
  'VU': '바누아투',
  'FJ': '피지',
  'PW': '팔라우',
  'CK': '쿡 제도',
  'NU': '니우에',
  'WS': '사모아',
  'KI': '키리바시',
  'NC': '누벨칼레도니',
  'TV': '투발루',
  'TK': '토켈라우',
  'FM': '미크로네시아 연방',
  'MH': '마셜 제도',
  'KP': '북한',
  'HK': '홍콩',
  'MO': '마카오',
  'KH': '캄보디아',
  'LA': '라오스',
  'BD': '방글라데시',
  'TW': '대만',
  'MV': '몰디브',
  'LB': '레바논',
  'JO': '요르단',
  'SY': '시리아',
  'IQ': '이라크',
  'KW': '쿠웨이트',
  'SA': '사우디아라비아',
  'YE': '예멘',
  'OM': '오만',
  'PS': '팔레스타인',
  'AE': '아랍에미리트',
  'IL': '이스라엘',
  'BH': '바레인',
  'QA': '카타르',
  'BT': '부탄',
  'MN': '몽골',
  'NP': '네팔',
  'TJ': '타지키스탄',
  'TM': '투르크메니스탄',
  'AZ': '아제르바이잔',
  'GE': '조지아',
  'KG': '키르기스스탄',
  'UZ': '우즈베키스탄',
  'BS': '바하마',
  'BB': '바베이도스',
  'AI': '앵귈라',
  'AG': '앤티가 바부다',
  'KY': '케이맨 제도',
  'BM': '버뮤다',
  'GD': '그레나다',
  'MS': '몬트세랫',
  'GU': '괌',
  'AS': '아메리칸사모아',
  'SX': '신트마르턴',
  'LC': '세인트루시아',
  'DM': '도미니카 연방',
  'PR': '푸에르토리코',
  'DO': '도미니카 공화국',
  'TT': '트리니다드 토바고',
  'JM': '자메이카',
};
